version: '3.1'

services:
  mail:
    image: mailhog/mailhog
    ports:
      - 8082:8025
  sharetribe:
    build: ./sharetribe/
    image: kw/sharetribe:latest
    environment:
      - MEMCACHIER_GREEN_SERVERS=memcached
    ports:
      - 8080:3000
  worker:
    image: kw/sharetribe:latest
    environment:
      - QUEUES=default,paperclip,mailers
      - MAGICK_MAP_LIMIT=64MiB
      - MAGICK_MEMORY_LIMIT=256MiB
      - MAGICK_TIME_LIMIT=30
    command: bundle exec rake jobs:work
  memcached:
    image: memcached:latest
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

networks:
  default:
    external:
      name: sharetribe        
        
